import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

//Components
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer"

//Font-awesome
import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false;

import { AuthProvider } from "./context/AuthContext";
import { CartProvider } from "./context/CartContext";
import { ScreenProvider } from "./context/MobileContext";
// import 'flowbite';
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Apple Heaven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <CartProvider>
            <ScreenProvider>
              <Header />
              <main className="flex-grow">
                {children}
              </main>
              <Footer />
            </ScreenProvider>
          </CartProvider>
        </AuthProvider>
        <Script src="/path/to/flowbite/dist/flowbite.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}

